BOARD_TAG		= uno
ARDUINO_LIBS 		= Wire Wire/utility ZumoMotors LSM303
				

://github.com/pololu/lsm303-arduino/archive/master.zip
ARDUINO_SKETCHBOOK	= /home/pi/IndoorDrone/ZumoNavigation/arduino/
include ../../Arduino-Makefile/Arduino.mk
